/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs1_ra11_2014_Stat */

#ifndef _Included_rtrk_pnrs1_ra11_2014_Stat
#define _Included_rtrk_pnrs1_ra11_2014_Stat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs1_ra11_2014_Stat
 * Method:    count
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_rtrk_pnrs1_ra11_12014_Stat_count
  (JNIEnv *, jobject, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
